### ISSUE TITLE
Odoo error on count method

### ISSUE THREAD

**Issue by JeuFore** [Ang3/php-odoo-api-client#26]
Hello,
I started to test version 7.0.5, but I detected a problem on ORM query method.
The count method always returns an Odoo error.

For example, I made a request like this:

```php
$pickingsDone = $this->rm
    ->createQueryBuilder('stock.picking')
    ->select(['id'])
    ->where($this->rm->expr()->in('id', $productOrder['picking_ids']))
    ->andWhere($this->rm->expr()->eq('state', 'done'))
    ->getQuery()
    ->addOption('context', ['lang' => $request->getAttribute('lang')])
    ->count();
```

But, it throws me the Odoo error:

```php
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py", line 69, in xmlrpc_2
    response = self._xmlrpc(service)
  File "/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py", line 49, in _xmlrpc
    result = dispatch_rpc(service, method, params)
  File "/home/odoo/src/odoo/odoo/http.py", line 120, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 40, in dispatch
    res = fn(db, uid, *params)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 178, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File "/home/odoo/src/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 185, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 169, in execute_cr
    result = odoo.api.call_kw(recs, method, args, kw)
  File "/home/odoo/src/odoo/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/models.py", line 1558, in search_count
    res = self.search(args, count=True)
  File "/home/odoo/src/odoo/odoo/models.py", line 1581, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/src/odoo/odoo/models.py", line 4145, in _search
    if expression.is_false(self, args):
  File "/home/odoo/src/odoo/odoo/osv/expression.py", line 227, in is_false
    elif token[1] == 'in' and not token[2]:
IndexError: string index out of range
```

**Comment by Ang3** [comment]
Hello,

Thank you for your feeback. What is the type of the variable `$productOrder['picking_ids']`? Is it an empty array? Null values? 
I'll check it quickly.

**Comment by JeuFore** [comment]
Hello,
The variable is a non-empty array containing integers, such as

```php
array(1) {
  [0]=>
  int(44836)
}
```

**Comment by Ang3** [comment]
Thanks. I'm trying to understand the odoo response. Could you add an ID in the criteria `in` and check if it works?
(remove options too in another test)
