### ISSUE TITLE
Successfully calling a method on an object results in a fatal error

### ISSUE THREAD

**Issue by linghenrik** [Ang3/php-odoo-api-client#7]
Hello

I am calling action_post on account.move. On the admin side I see that the status was changed from draft to posted, as it should, but the following error comes up:

````
[22-Jan-2021 11:07:46 Europe/Tallinn] PHP Fatal error:  Uncaught Ang3\Component\XmlRpc\Exception\RemoteException: Traceback (most recent call last):
  File "/usr/lib/python3.7/xmlrpc/client.py", line 510, in __dump
    f = self.dispatch[type(value)]
KeyError: <class 'odoo.api.account.move'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/sources/odoo/odoo/addons/base/controllers/rpc.py", line 69, in xmlrpc_2
    response = self._xmlrpc(service)
  File "/opt/odoo/sources/odoo/odoo/addons/base/controllers/rpc.py", line 50, in _xmlrpc
    return dumps((result,), methodresponse=1, allow_none=False)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 971, in dumps
    data = m.dumps(params)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 502, in dumps
    dump(v, write)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 514, in __dump
    raise TypeError("cannot marshal %s objects" % type(value))
TypeError: cannot marshal <class 'odoo.api.account.move'> objects
 in PHP/vendor/ang3/php-odoo-api-client/src/Endpoint.php on line 40
````

Any ideas?

Thanks.

**Comment by Ang3** [comment]
Hi,

Thank you for your feedback. Just a question:
- When you say "Successfully calling", is that means the command did its job?

This "marshall" error usually occurs when Odoo returns no data, but the command works in that case.

**Comment by linghenrik** [comment]
Hi,

Yes, the command itself worked.

**Comment by linghenrik** [comment]
Turns on the API returned the whole record object and not just the ID. Had another function developed that returned just the ID and that did the trick. Case closed from my point of view.

Thank you for the help and the package! Sure made my life easier

**Comment by Ang3** [comment]
Hi,

Thank you for your feedback. The version ```7.0``` will fix this issue by a "response trick". ;)
